type
  TagType* = enum
    ttUnknown = ""
    ttApplet = "applet"
    ttBig = "big"
    ttHtml = "html"
    ttBase = "base"
    ttBasefont = "basefont"
    ttBgsound = "bgsound"
    ttHead = "head"
    ttLink = "link"
    ttListing = "listing"
    ttMeta = "meta"
    ttStyle = "style"
    ttTitle = "title"
    ttBody = "body"
    ttAddress = "address"
    ttArticle = "article"
    ttAside = "aside"
    ttFooter = "footer"
    ttHeader = "header"
    ttH1 = "h1"
    ttH2 = "h2"
    ttH3 = "h3"
    ttH4 = "h4"
    ttH5 = "h5"
    ttH6 = "h6"
    ttHgroup = "hgroup"
    ttMain = "main"
    ttNav = "nav"
    ttSearch = "search"
    ttSection = "section"
    ttBlockquote = "blockquote"
    ttDd = "dd"
    ttDiv = "div"
    ttDl = "dl"
    ttDt = "dt"
    ttFigcaption = "figcaption"
    ttFigure = "figure"
    ttHr = "hr"
    ttLi = "li"
    ttOl = "ol"
    ttP = "p"
    ttPre = "pre"
    ttUl = "ul"
    ttA = "a"
    ttAbbr = "abbr"
    ttB = "b"
    ttBdi = "bdi"
    ttBdo = "bdo"
    ttBr = "br"
    ttNobr = "nobr"
    ttCite = "cite"
    ttCode = "code"
    ttData = "data"
    ttDfn = "dfn"
    ttEm = "em"
    ttEmbed = "embed"
    ttI = "i"
    ttKbd = "kbd"
    ttMark = "mark"
    ttMarquee = "marquee"
    ttQ = "q"
    ttRb = "rb"
    ttRp = "rp"
    ttRt = "rt"
    ttRtc = "rtc"
    ttRuby = "ruby"
    ttS = "s"
    ttSamp = "samp"
    ttSmall = "small"
    ttSpan = "span"
    ttStrong = "strong"
    ttSub = "sub"
    ttSup = "sup"
    ttTime = "time"
    ttU = "u"
    ttVar = "var"
    ttWbr = "wbr"
    ttArea = "area"
    ttAudio = "audio"
    ttImg = "img"
    ttImage = "image"
    ttMap = "map"
    ttTrack = "track"
    ttVideo = "video"
    ttIframe = "iframe"
    ttObject = "object"
    ttParam = "param"
    ttPicture = "picture"
    ttPortal = "portal"
    ttSource = "source"
    ttCanvas = "canvas"
    ttNoscript = "noscript"
    ttNoembed = "noembed"
    ttPlaintext = "plaintext"
    ttXmp = "xmp"
    ttScript = "script"
    ttSlot = "slot"
    ttDel = "del"
    ttIns = "ins"
    ttCaption = "caption"
    ttCol = "col"
    ttColgroup = "colgroup"
    ttTable = "table"
    ttTbody = "tbody"
    ttTd = "td"
    ttTfoot = "tfoot"
    ttTh = "th"
    ttThead = "thead"
    ttTr = "tr"
    ttButton = "button"
    ttDatalist = "datalist"
    ttFieldset = "fieldset"
    ttForm = "form"
    ttInput = "input"
    ttKeygen = "keygen"
    ttLabel = "label"
    ttLegend = "legend"
    ttMeter = "meter"
    ttOptgroup = "optgroup"
    ttOption = "option"
    ttOutput = "output"
    ttProgress = "progress"
    ttSelect = "select"
    ttSelectedcontent = "selectedcontent"
    ttTextarea = "textarea"
    ttDetails = "details"
    ttDialog = "dialog"
    ttMenu = "menu"
    ttSummary = "summary"
    ttBlink = "blink"
    ttCenter = "center"
    ttContent = "content"
    ttDir = "dir"
    ttFont = "font"
    ttFrame = "frame"
    ttNoframes = "noframes"
    ttFrameset = "frameset"
    ttStrike = "strike"
    ttTt = "tt"
    ttTemplate = "template"
    ttMath = "math"
    ttSvg = "svg"
    ttCharset = "charset"
    ttHttpEquiv = "http-equiv"
    ttTyp = "type"
    ttDefinitionurl = "definitionurl"
    ttAnnotationXml = "annotation-xml"
    ttForeignObject = "foreignObject"
    ttDesc = "desc"
    ttEncoding = "encoding"
    ttMi = "mi"
    ttMo = "mo"
    ttMn = "mn"
    ttMs = "ms"
    ttMtext = "mtext"
    ttMglyph = "mglyph"
    ttMalignmark = "malignmark"
    ttColor = "color"
    ttFace = "face"
    ttSize = "size"

  QuirksMode* = enum
    qmNoQuirks, qmQuirks, qmLimitedQuirks

  Namespace* = enum
    nsNone = ""
    nsHTML = "http://www.w3.org/1999/xhtml",
    nsMathML = "http://www.w3.org/1998/Math/MathML",
    nsSVG = "http://www.w3.org/2000/svg",
    nsXLink = "http://www.w3.org/1999/xlink",
    nsXml = "http://www.w3.org/XML/1998/namespace",
    nsXmlns = "http://www.w3.org/2000/xmlns/"
    nsUnknown = ""

  ParsedAttr*[Atom] = object
    name*: Atom ## This is the qualified name.
    namespace*: Atom
    value*: string

  ParsedAttrs*[Atom] = seq[ParsedAttr[Atom]]

const AllTagTypes* = {TagType.low..TagType.high}

const HTagTypes* = {
  ttH1, ttH2, ttH3, ttH4, ttH5, ttH6
}

const FormAssociatedElements* = {
  ttButton, ttFieldset, ttInput, ttObject, ttOutput, ttSelect,
  ttTextarea, ttImg
}

const ListedElements* = {
  ttFieldset, ttInput, ttObject, ttOutput, ttSelect, ttTextarea
}
